fix

diff --git a/infra b/infra
--- a/infra
+++ b/infra
@@ -1,4 +1,5 @@
 #!/bin/bash
+# Docker-compose wrapper for easy deployment
 
 # Variables
 _program_name=$(basename $0)
@@ -18,17 +19,34 @@ _file_exist() {
   [[ -f "$1" ]]
 }
 
+_confirm() {
+  read -ep "${1:-Are you sure?} [y/N]: " _confirmation
+  _confirmation="${_confirmation:-n}"
+
+  case "${_confirmation}" in
+  [yY])
+    :
+    ;;
+  *)
+    exit 0
+    ;;
+  esac
+}
+
 _throw_error() {
   local _message=$1
   shift
 
-  echo "Error: ${_message}"
+  {
+    echo "Error: ${_message}"
 
-  for _error in "$@"; do
-  echo "${_error}"
-  done
+    for _error in "$@"; do
+      echo "${_error}"
+    done
 
-  echo "Run '${_program_name} help' for usage."
+    echo "Run '${_program_name} help' for usage."
+  } >&2
+
   exit 1
 }
 
@@ -52,7 +70,7 @@ _docker_compose() {
       " - DOCKER_COMPOSE_USER is not set" \
       " - DOCKER_COMPOSE_USER_GROUP is not set"
   fi
-  docker-compose --env-file ${_docker_compose_env_file} "$@"
+  docker-compose --env-file "${_docker_compose_env_file}" "$@"
 }
 
 _docker_compose_run() {
@@ -68,6 +86,8 @@ _env_check() {
     echo -n "Creating .env file ... "
     echo "APP_KEY=" >.env
     echo "Done"
+  else
+    _confirm "The infrastructure is already deployed. Are you sure you want to continue?"
   fi
 }
 
@@ -89,6 +109,7 @@ _do_up() {
 
 _do_down() {
   _no_argument "$@"
+  _confirm "Are you sure you want to stop the infrastructure?"
   _docker_compose "down"
 }
 
@@ -101,6 +122,7 @@ _do_logs() {
 }
 
 _do_restart() {
+  _confirm "Are you sure you want to restart the services?"
   _docker_compose "restart" "$@"
 }
 
@@ -143,7 +165,7 @@ Usage:
 Available commands:
    init                  Initialize the infrastructure for the first time
    up                    Start the infrastructure
-   down                  Stop infrastructure
+   down                  Stop the infrastructure
    build [services?]     Build image for all or given services
    logs [services?]      View logs for all or given services
    restart [services?]   Restart all or given services
